site_name: highentDCA & adabmDCApy
site_dir: site
docs_dir: docs
nav:
  - Home: index.md
  - highentDCA (Entropy Decimation):
      - Introduction: highentDCA_index.md
      - Installation: highentDCA_installation.md
      - Usage Guide: highentDCA_usage.md
      - API Reference:
          - Overview: api/highentDCA_overview.md
          - Checkpoint: api/highentDCA_checkpoint.md
          - Training: api/highentDCA_training.md
          - edDCA Model: api/highentDCA_models.edDCA.md
          - Entropy Computation: api/highentDCA_entropy.md
  - adabmDCA (Base Framework):
      - Home: index.md
      - Installation: installation.md
      - Input data and preprocessing: preprocessing.md
      - Training: training.md
      - Applications: applications.md
      - Quicklist: quicklist.md
      - Script arguments: script_arguments.md

theme: 
  name: material
  features:
    - content.code.annotate # Optional syntax highlighting
    - content.tabs.link     # Optional tabs support

markdown_extensions:
    - pymdownx.arithmatex:  # Enables LaTeX math
        generic: true       # Uses KaTeX by default
    - pymdownx.snippets
    - admonition  # Enables basic !!! syntax
    - pymdownx.details  # For richer styles (optional)

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
